import "./global.css";

export const metadata = {
  title: "3SP Courses",
  description: "Generated by BCC",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
